apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config
  namespace: logging
  labels:
    k8s-app: curator
data:
  curator.yml.sample: |-
    client:
      hosts:
        - "http://{{ELASTIC_URL}}"
      port: 9200
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      #http_auth: "{{ELASTIC_USER}}:{{ELASTIC_PASSWORD}}"
      timeout: 30
      master_only: False
    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
  curator-actions.yml: |-
    # Deletes indices older than 60 days, close the ones older than 30 days
    actions:
      1:
       action: delete_indices
       description: >-
         Delete indices older than 5 days ('^apm-|^filebeat-')
       options:
         ignore_empty_list: True
         disable_action: False
         continue_if_exception: False
       filters:
       - filtertype: pattern
         kind: regex
         value: '^apm-|^filebeat-|^logstash-|^fluent'
       - filtertype: age
         source: name
         direction: older
         timestring: '%Y.%m.%d'
         unit: days
         unit_count: RETENTION_DAYS
      2:
       action: close
       description: >-
         Close indices older than 5 days ('^apm-|^filebeat-')
       options:
         delete_aliases: False
         ignore_empty_list: True
         continue_if_exception: False
         disable_action: True
       filters:
       - filtertype: pattern
         kind: regex
         value: '^apm-|^filebeat-|^logstash-|^fluent'
       - filtertype: age
         source: name
         direction: older
         timestring: '%Y.%m.%d'
         unit: days
         unit_count: RETENTION_DAYS
 
