apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-client
  namespace: logging
  labels:
    app: elasticsearch-client
    env: dev
spec:
  replicas: 2 # scale as desired
  selector:
    matchLabels:
      app: elasticsearch-client
  template:
    metadata:
      labels:
        app: elasticsearch-client
        env: dev
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - /bin/sh
        - -c
        - |
          sysctl -w vm.max_map_count=262144
          sleep 30
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch-client
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: elasticsearch-discovery
        - name: cluster.initial_master_nodes
          value: elasticsearch-master-0, elasticsearch-master-1,elasticsearch-master-2
        - name: cluster.name
          value: elasticsearch
        - name: xpack.security.enabled
          value: "true"
        - name: node.master
          value: "false"
        - name: network.host
          value: "_site_,_lo_"
        - name: http.host
          value: 0.0.0.0
        - name: node.ingest
          value: "true"
        - name: node.data
          value: "false"
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx256m
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          limits:
            cpu: 1
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - emptyDir:
          medium: ""
        name: "storage"
