apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: grafana-svc
  labels:
    k8s-app: grafana
spec:
  selector:
    k8s-app: grafana
  ports:
  - name: http
    nodePort: 31114
    port: 3000
  type: NodePort
