apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: logging
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:4.2
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-volume
              mountPath: /data/db
      volumes:
        - emptyDir:
            medium: ""    
          name: mongo-persistent-volume
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: logging
  labels:
    app: mongo
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb
